/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editortexto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author Inti Velasquez
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    Connection con = null;
    Statement db = null;

    public main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdLogin = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pwfPass = new javax.swing.JPasswordField();
        bCheckCredentials = new javax.swing.JButton();
        bExitLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdRegister = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        tfRUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pwfRPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        pwfRPass2 = new javax.swing.JPasswordField();
        bRegisterUser = new javax.swing.JButton();
        bExitRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jdMain = new javax.swing.JDialog();
        bLogin = new javax.swing.JButton();
        bRegister = new javax.swing.JButton();
        bExit = new javax.swing.JButton();

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        bCheckCredentials.setText("Iniciar Sesion");
        bCheckCredentials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCheckCredentialsMouseClicked(evt);
            }
        });

        bExitLogin.setText("Salir");

        jLabel3.setText("Ingrese su usuario y contraseña para iniciar sesion. ");

        jLabel4.setText("Si no tiene una cuenta, Registrese en el menu principal.");

        javax.swing.GroupLayout jdLoginLayout = new javax.swing.GroupLayout(jdLogin.getContentPane());
        jdLogin.getContentPane().setLayout(jdLoginLayout);
        jdLoginLayout.setHorizontalGroup(
            jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLoginLayout.createSequentialGroup()
                .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdLoginLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCheckCredentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bExitLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jdLoginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUser)
                                .addComponent(pwfPass, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                            .addComponent(jLabel4))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jdLoginLayout.setVerticalGroup(
            jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdLoginLayout.createSequentialGroup()
                        .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jdLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(bCheckCredentials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bExitLogin)
                        .addGap(23, 23, 23))
                    .addGroup(jdLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel5.setText("Nombre de usuario:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Confirme contraseña:");

        bRegisterUser.setText("Registrarse");
        bRegisterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegisterUserMouseClicked(evt);
            }
        });

        bExitRegister.setText("Salir");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Registrar nuevo usuario");

        javax.swing.GroupLayout jdRegisterLayout = new javax.swing.GroupLayout(jdRegister.getContentPane());
        jdRegister.getContentPane().setLayout(jdRegisterLayout);
        jdRegisterLayout.setHorizontalGroup(
            jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdRegisterLayout.createSequentialGroup()
                .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdRegisterLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRUser)
                            .addComponent(pwfRPass)
                            .addComponent(pwfRPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)))
                    .addGroup(jdRegisterLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(bExitRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdRegisterLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(bRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdRegisterLayout.createSequentialGroup()
                .addGap(0, 202, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(152, 152, 152))
        );
        jdRegisterLayout.setVerticalGroup(
            jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdRegisterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfRUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pwfRPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwfRPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(bRegisterUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExitRegister)
                .addContainerGap())
        );

        javax.swing.GroupLayout jdMainLayout = new javax.swing.GroupLayout(jdMain.getContentPane());
        jdMain.getContentPane().setLayout(jdMainLayout);
        jdMainLayout.setHorizontalGroup(
            jdMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdMainLayout.setVerticalGroup(
            jdMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLogin.setText("Log in");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });

        bRegister.setText("Registrarse");
        bRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegisterMouseClicked(evt);
            }
        });

        bExit.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(bLogin)
                .addGap(30, 30, 30)
                .addComponent(bRegister)
                .addGap(35, 35, 35)
                .addComponent(bExit)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        tfUser.setText("");
        pwfPass.setText("");
        jdLogin.pack();
        jdLogin.setLocationRelativeTo(this);
        jdLogin.setModal(true);
        jdLogin.setVisible(true);
    }//GEN-LAST:event_bLoginMouseClicked

    private void bCheckCredentialsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCheckCredentialsMouseClicked
        try {
            String user = tfUser.getText();
            String password = String.valueOf(pwfPass.getPassword());
            if (!user.equals("") && !password.equals("")) {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/holis?autoReconnect=true&useSSL=false", user, password);
                JOptionPane.showMessageDialog(jdLogin, "Bienvenido " + user);
                jdLogin.dispose();
                jdRegister.pack();
                jdRegister.setLocationRelativeTo(this);
                jdRegister.setModal(true);
                jdRegister.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(jdLogin, "Usuario y/o contraseña no pueden ser vacios");
                tfUser.setText("");
                pwfPass.setText("");
            }
        } catch (InputMismatchException | SQLException e) {
            con = null;
            tfUser.setText("");
            pwfPass.setText("");
            JOptionPane.showConfirmDialog(jdLogin, "Usuario no encontrado. Verifique sus credenciales o registre una cuenta primero");
        }
    }//GEN-LAST:event_bCheckCredentialsMouseClicked

    private void bRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegisterMouseClicked
        tfRUser.setText("");
        pwfRPass.setText("");
        pwfRPass2.setText("");
        jdRegister.pack();
        jdRegister.setLocationRelativeTo(this);
        jdRegister.setModal(true);
        jdRegister.setVisible(true);
    }//GEN-LAST:event_bRegisterMouseClicked

    private void bRegisterUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegisterUserMouseClicked
        System.out.println("Register no hace nada hasta aclarar como se debe implementar");
        /*String rUser = tfRUser.getText();
        String rPass = String.valueOf(pwfRPass.getPassword());
        String rPass2 = String.valueOf(pwfRPass2.getPassword());
        try {

            if (!rUser.equals("") && !rPass.equals("") && !rPass2.equals("")) {
                if (rUser.length() < 4 || rPass.length() < 4) {
                    JOptionPane.showMessageDialog(jdRegister, "Usuario y contraseña deben tener 4 caracter como minimo");
                } else if (!rPass.equals(rPass2)) {
                    JOptionPane.showMessageDialog(jdRegister, "Las contraseñas no coinciden");
                    pwfRPass.setText("");
                    pwfRPass2.setText("");
                } else if (rUser.length() > 4 && rPass.length() > 4 && rPass.equals(rPass2)) {
                    Connection tempCon=DriverManager.getConnection("jdbc:mysql://localhost:3306/holis?autoReconnect=true&useSSL=false","admin","pokemon123");
                    Statement tempSt=tempCon.createStatement();
                    ResultSet userExists = tempSt.executeQuery("select exists(select 1 from Users where user='"+rUser+"')");
                    if(userExists.next()){
                        JOptionPane.showMessageDialog(jdRegister, "El usuario ya existe");
                        tfRUser.setText("");
                        pwfRPass.setText("");
                        pwfRPass2.setText("");
                        tempSt.close();
                        tempCon.close();
                    }else{
                        
                    }
                }
            } else {
                JOptionPane.showMessageDialog(jdRegister, "Debe llenar todos los campos");
                tfRUser.setText("");
                pwfRPass.setText("");
                pwfRPass2.setText("");
            }
        } catch (InputMismatchException | SQLException e) {
            JOptionPane.showMessageDialog(jdRegister, "Ocurrio un error al registrar el usuario. El usuario ya existe o se corto la coneccion a la base de datos.\n\t\tIntente de nuevo");
        }*/
    }//GEN-LAST:event_bRegisterUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCheckCredentials;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bExitLogin;
    private javax.swing.JButton bExitRegister;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bRegister;
    private javax.swing.JButton bRegisterUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JDialog jdLogin;
    private javax.swing.JDialog jdMain;
    private javax.swing.JDialog jdRegister;
    private javax.swing.JPasswordField pwfPass;
    private javax.swing.JPasswordField pwfRPass;
    private javax.swing.JPasswordField pwfRPass2;
    private javax.swing.JTextField tfRUser;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
